var DependenciasMunicipales ={
"type": "FeatureCollection",
"name": "DependenciasMunicipales",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "ID": "1", "DEPENDENCI": "CASA MUNICIPAL", "DIRECCION": "Rivadavia 448", "ESTADO_GEN": "B", "CORROBORAR": null, "CARACTERIS": "Frente a Plaza Municipal de Godoy Cruz. (Zona Centro Civico)", "SERVICIOS": "sanitarios-climatizacion", "Nombre_1": "CASA MUNICIPAL" }, "geometry": { "type": "Point", "coordinates": [ -68.843189939118346, -32.925125504739498 ] } },
{ "type": "Feature", "properties": { "ID": "2", "DEPENDENCI": "CORRALON MUNICIPAL", "DIRECCION": "Juncal 399", "ESTADO_GEN": "B", "CORROBORAR": "Gustavo Bonano", "CARACTERIS": "Corredor del Oeste y Canal Frias. (Zona Residencial Mixta)", "SERVICIOS": "sanitarios-climatizacion", "Nombre_1": "CORRALON MUNICIPAL" }, "geometry": { "type": "Point", "coordinates": [ -68.865319697938119, -32.923347138359098 ] } },
{ "type": "Feature", "properties": { "ID": "3", "DEPENDENCI": "SEDE GUEMES", "DIRECCION": "Guemes esq. Ciclovia", "ESTADO_GEN": "M", "CORROBORAR": "Yamel", "CARACTERIS": "A 2 cuadras de calle San Martin Sur. (Zona Residencial Mixta)", "SERVICIOS": "sanitarios", "Nombre_1": "SEDE GUEMES" }, "geometry": { "type": "Point", "coordinates": [ -68.851430613889278, -32.928045742832175 ] } },
{ "type": "Feature", "properties": { "ID": "4", "DEPENDENCI": "SEDE LIBERTAD", "DIRECCION": "Joaquin V. Gonzalez 450", "ESTADO_GEN": "B", "CORROBORAR": "Pedro San Martin", "CARACTERIS": "Sector Suroeste del Departamento. Gran Capacidad de Estacionamiento. Zona Comercial Mixta", "SERVICIOS": "sanitarios-climatizacion", "Nombre_1": "SEDE LIBERTAD" }, "geometry": { "type": "Point", "coordinates": [ -68.857921022327645, -32.929347957935548 ] } },
{ "type": "Feature", "properties": { "ID": "5", "DEPENDENCI": "CAU I", "DIRECCION": "Perito Moreno 72", "ESTADO_GEN": "B", "CORROBORAR": "Verificar", "CARACTERIS": "Frente a Plaza Municipal de Godoy Cruz. (Zona Centro Civico)", "SERVICIOS": "sanitarios-climatizacion", "Nombre_1": "CAU I" }, "geometry": { "type": "Point", "coordinates": [ -68.84344331843856, -32.92563103186724 ] } },
{ "type": "Feature", "properties": { "ID": "6", "DEPENDENCI": "CAU II", "DIRECCION": "Paso de los Andes esq. Laprida", "ESTADO_GEN": "B", "CORROBORAR": "Verificar", "CARACTERIS": "Sector Suroeste del Departamento. Zona Comercial Mixta", "SERVICIOS": "sanitarios-climatizacion", "Nombre_1": "CAU II" }, "geometry": { "type": "Point", "coordinates": [ -68.859673237182719, -32.909873260111382 ] } },
{ "type": "Feature", "properties": { "ID": "7", "DEPENDENCI": "CAU III", "DIRECCION": "Sarmiento 585 (Paseo Stare)", "ESTADO_GEN": "B", "CORROBORAR": "Verificar", "CARACTERIS": "Nudo Neuralgico de transporte. Ubicado en esquina Sarmiento y Cervantes. Zona Comercial Mixta", "SERVICIOS": "sanitarios-climatizacion", "Nombre_1": "CAU III" }, "geometry": { "type": "Point", "coordinates": [ -68.840297517226787, -32.938669034643574 ] } },
{ "type": "Feature", "properties": { "ID": "8", "DEPENDENCI": "PESCARMONA GALPONES", "DIRECCION": "Balcarce esq. Rivadavia", "ESTADO_GEN": null, "CORROBORAR": null, "CARACTERIS": "C�ntrico (1 cuadra plaza Municipal de Godoy Cruz). Sector Espacio verde", "SERVICIOS": "no posee", "Nombre_1": "GALPONES PESCARMONA" }, "geometry": { "type": "Point", "coordinates": [ -68.842018547063731, -32.92408172115524 ] } },
{ "type": "Feature", "properties": { "ID": "9", "DEPENDENCI": "CRISTOFORO COLOMBO", "DIRECCION": "Antonio Tomba 246", "ESTADO_GEN": "B", "CORROBORAR": "Guido Zalazar", "CARACTERIS": "A 3 cuadras aprox. Plaza Municipal. Zona Residencial Mixta", "SERVICIOS": "sanitarios-climatizacion", "Nombre_1": "CRISTOFORO COLOMBO" }, "geometry": { "type": "Point", "coordinates": [ -68.841979565575357, -32.921909041183874 ] } },
{ "type": "Feature", "properties": { "ID": "10", "DEPENDENCI": "CINE TEATRO PLAZA MUNICIPAL", "DIRECCION": "Colon 27", "ESTADO_GEN": "B", "CORROBORAR": "Guido Zalazar", "CARACTERIS": "Frente a Plaza Municipal de Godoy Cruz. (Zona Centro Civico)", "SERVICIOS": "sanitarios-climatizacion", "Nombre_1": "CINE TEATRO PLAZA" }, "geometry": { "type": "Point", "coordinates": [ -68.845222820783789, -32.924899734369923 ] } },
{ "type": "Feature", "properties": { "ID": "11", "DEPENDENCI": "COMISARIA 7 ma", "DIRECCION": "Lavalle 88", "ESTADO_GEN": "?", "CORROBORAR": "Alicia Ruiz", "CARACTERIS": "Frente a Plaza Municipal de Godoy Cruz. (Zona Centro Civico)", "SERVICIOS": "?", "Nombre_1": "EX COMISARIA 7" }, "geometry": { "type": "Point", "coordinates": [ -68.845086385796918, -32.925845348293038 ] } },
{ "type": "Feature", "properties": { "ID": "12", "DEPENDENCI": "CASA DEL FUTURO", "DIRECCION": "Sarmiento 2291", "ESTADO_GEN": "?", "CORROBORAR": "Lucas Videla", "CARACTERIS": "Cerca del l�mite entre Godoy Cruz y Maip�. Zona Comercial Mixta", "SERVICIOS": "?", "Nombre_1": "CASA DEL FUTURO" }, "geometry": { "type": "Point", "coordinates": [ -68.817781842314119, -32.943654704232529 ] } },
{ "type": "Feature", "properties": { "ID": "13", "DEPENDENCI": "MEDIATECA MUNICIPAL", "DIRECCION": "Antonio Tomba 54", "ESTADO_GEN": "B", "CORROBORAR": null, "CARACTERIS": "C�ntrico (media cuadra plaza Municipal de Godoy Cruz). Zona Centro Civico", "SERVICIOS": "sanitarios-climatizacion", "Nombre_1": "MEDIATECA MUNICPAL" }, "geometry": { "type": "Point", "coordinates": [ -68.843456961900415, -32.92412425800525 ] } },
{ "type": "Feature", "properties": { "ID": "14", "DEPENDENCI": "BODEGA ARIZU", "DIRECCION": "San Martin entre Minuzzi y Lisandro de la Torre", "ESTADO_GEN": null, "CORROBORAR": null, "CARACTERIS": "Lugar Centrico. (Zona Comercial)", "SERVICIOS": "no posee", "Nombre_1": "BODEGA ARIZU" }, "geometry": { "type": "Point", "coordinates": [ -68.843870164674868, -32.908618211886939 ] } },
{ "type": "Feature", "properties": { "ID": null, "DEPENDENCI": "CEMENTERIO", "DIRECCION": "Cervantes y Alsina", "ESTADO_GEN": null, "CORROBORAR": null, "CARACTERIS": null, "SERVICIOS": null, "Nombre_1": "CEMENTERIO" }, "geometry": { "type": "Point", "coordinates": [ -68.839503856105438, -32.933435768802639 ] } },
{ "type": "Feature", "properties": { "ID": null, "DEPENDENCI": "CASA DE LOS ABUELOS", "DIRECCION": "Derqui y Marmol", "ESTADO_GEN": null, "CORROBORAR": null, "CARACTERIS": null, "SERVICIOS": null, "Nombre_1": "CASA DE LOS ABUELOS" }, "geometry": { "type": "Point", "coordinates": [ -68.85714856266037, -32.916746261269061 ] } },
{ "type": "Feature", "properties": { "ID": null, "DEPENDENCI": "JUZGADO DE TRANSITO", "DIRECCION": "J.V.Gonzalez y Ing.Cipolletti", "ESTADO_GEN": null, "CORROBORAR": null, "CARACTERIS": null, "SERVICIOS": null, "Nombre_1": "JUZGADO DE TRANSITO" }, "geometry": { "type": "Point", "coordinates": [ -68.858653118261117, -32.932634056201437 ] } }
]
}
