var Mastiles ={
"type": "FeatureCollection",
"name": "Mastiles",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Cayetano Silva y Marcos Sastre", "Nombre_Descripcion": "Barrio Gas del Estado I", "Ubicaci__n": "Cayetano Silva y Marcos Sastre", "Posee_Mastil": "Posee Mastil: No", "Posee_Bandera": "No", "Posee_Placa_Recordatoria": "No", "Altura_Aprox_": "8 - 10 metros", "Estado": "solo conserva la base del Mastil", "Distrito": "Distrito Villa del Parque", "Observaciones_": "Ubicado en vereda Posee Mastil: Sin sede barrial", "Fotos": "BarrioGasI.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8760512, -32.9090515 ] } },
{ "type": "Feature", "properties": { "Name": "Unión Vecinal City Fhaters", "Nombre_Descripcion": "Union Vecinal City Fhaters", "Ubicaci__n": "General Alvear 730 ", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "Posee Mastil: Si", "Posee_Placa_Recordatoria": "No", "Altura_Aprox_": "", "Estado": "", "Distrito": "Distrito Villa Hipódromo", "Observaciones_": "", "Fotos": "UnioVecinalCityFhater.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8626441, -32.9167642 ] } },
{ "type": "Feature", "properties": { "Name": "Villa Emilia", "Nombre_Descripcion": "Villa Emilia", "Ubicaci__n": "Florencio Sanchez y Luis Ma. Drago", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "", "Posee_Placa_Recordatoria": "", "Altura_Aprox_": "", "Estado": "", "Distrito": "Distrito Centro", "Observaciones_": "", "Fotos": "BarrioVillaEmilia.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8412691224724, -32.93286692032152 ] } },
{ "type": "Feature", "properties": { "Name": "Villa Edilco", "Nombre_Descripcion": "Villa Edilco", "Ubicaci__n": "Javier Morales y Cornelio Saavedra", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "Posee Mastil: Si", "Posee_Placa_Recordatoria": "No", "Altura_Aprox_": "8 - 10 metros", "Estado": "Bueno", "Distrito": "Distrito Las Tortugas", "Observaciones_": "", "Fotos": "VillaEdilco.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.84471983791448, -32.95241115350662 ] } },
{ "type": "Feature", "properties": { "Name": "Villa Ortiz", "Nombre_Descripcion": "Villa Ortiz", "Ubicaci__n": "Ciclovia Ernesto Contreras y A. Fleming", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "No", "Posee_Placa_Recordatoria": "No", "Altura_Aprox_": "6 metros", "Estado": "Bueno", "Distrito": "Distrito Villa Hipódromo", "Observaciones_": "", "Fotos": "BarrioVillaOrtiz.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8581664, -32.921532 ] } },
{ "type": "Feature", "properties": { "Name": "Barrio Manino", "Nombre_Descripcion": "Barrio de La Rosa Manino del Carmen", "Ubicaci__n": "Maza y Hungria", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "No", "Posee_Placa_Recordatoria": "No", "Altura_Aprox_": "7 - 8 metros", "Estado": "Regular", "Distrito": "Distrito Villa Marini", "Observaciones_": "", "Fotos": "BarrioManino.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8570532, -32.9229142 ] } },
{ "type": "Feature", "properties": { "Name": "U.V. Villa Hipodromo", "Nombre_Descripcion": "Unión Vecinal Villa Hipódromo", "Ubicaci__n": "General Alvear y Pdte. R.M. Ortiz", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "No", "Posee_Placa_Recordatoria": "No", "Altura_Aprox_": "5 - 6 metros", "Estado": "Bueno", "Distrito": "Villa Hipódromo", "Observaciones_": "", "Fotos": "U_V_Villa_Hipodromo.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8630651, -32.9106412 ] } },
{ "type": "Feature", "properties": { "Name": "Rivadavia y Renato Della Santa", "Nombre_Descripcion": "Centro Recreativo y Deportivo Villa Marini", "Ubicaci__n": "Rivadavia y Renato Della Santa", "Posee_Mastil": "Posee Mastil: Si ", "Posee_Bandera": "No", "Posee_Placa_Recordatoria": "No", "Altura_Aprox_": "8 metros", "Estado": "Bueno pero requiere limpieza", "Distrito": "Distrito Villa Marini", "Observaciones_": "Posee placa recordatoria sobre pared", "Fotos": "VillaMarini.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8607032, -32.9243623 ] } },
{ "type": "Feature", "properties": { "Name": "Espacio Integral  Comunitario Postas Argentinas", "Nombre_Descripcion": "Espacio Integral Comunitario", "Ubicaci__n": "Punilla 1400", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "NO", "Posee_Placa_Recordatoria": "No", "Altura_Aprox_": "6 metros", "Estado": "bUENO", "Distrito": "Distrito Villa Marini", "Observaciones_": "", "Fotos": "UnionVecinalPostasArgentinas.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8725713, -32.9361939 ] } },
{ "type": "Feature", "properties": { "Name": "Barrio Villa Jovita", "Nombre_Descripcion": "Barrio Villa Jovita", "Ubicaci__n": "Paraguay y Renato Della Santa", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "No", "Posee_Placa_Recordatoria": "Posee Mastil: Si", "Altura_Aprox_": "8 - 10 metros", "Estado": "Bueno", "Distrito": "Distrito Villa Hipódromo", "Observaciones_": "", "Fotos": "villaJovita.gif" }, "geometry": { "type": "Point", "coordinates": [ -68.8622606, -32.9047022 ] } },
{ "type": "Feature", "properties": { "Name": "Villa Clementina", "Nombre_Descripcion": "Villa Clementina", "Ubicaci__n": "Roca y Catamarca", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "No", "Posee_Placa_Recordatoria": "Posee Mastil: Si", "Altura_Aprox_": "6 - 10 metros", "Estado": "Bueno", "Distrito": "Distrito Las Tortugas", "Observaciones_": "", "Fotos": "VillaClementina.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8345315, -32.9444951 ] } },
{ "type": "Feature", "properties": { "Name": "Union Vecinal Gobernador Benegas", "Nombre_Descripcion": "Union Vecinal Gobernador Benegas", "Ubicaci__n": "Salvador Ma. Del Carril 1872", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "No", "Posee_Placa_Recordatoria": "No", "Altura_Aprox_": "6 - 8 metros", "Estado": "Bueno", "Distrito": "Distrito Las Tortugas", "Observaciones_": "", "Fotos": "UnionVecinalBenegas.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8408924, -32.948404 ] } },
{ "type": "Feature", "properties": { "Name": "Barrio Cremaschi (San Francisco del Monte)", "Nombre_Descripcion": "Barrio Cremaschi (San Francisco del Monte)", "Ubicaci__n": "Rodriguez Peña y Diamante", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "No", "Posee_Placa_Recordatoria": "No", "Altura_Aprox_": "8 - 10 metros", "Estado": "Regular", "Distrito": "Distrito San Francisco del Monte", "Observaciones_": "", "Fotos": "BarrioCremaschi.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8225932, -32.9264177 ] } },
{ "type": "Feature", "properties": { "Name": "Union Vecinal La Perla", "Nombre_Descripcion": "Union Vecinal La Perla", "Ubicaci__n": "Sarmiento 1940", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "No", "Posee_Placa_Recordatoria": "No", "Altura_Aprox_": "5 - 6 metros", "Estado": "Bueno", "Distrito": "Distrito San Francisco del Monte", "Observaciones_": "", "Fotos": "UnionVecinalLaPerla.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8235005, -32.9419739 ] } },
{ "type": "Feature", "properties": { "Name": "Asociación Vecinal Justo José de Urquiza - Barrio Ginner", "Nombre_Descripcion": "Asociación Vecinal Justo José de Urquiza - Barrio Ginner", "Ubicaci__n": "Italia y Jose Ingenieros", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "No", "Posee_Placa_Recordatoria": "Posee Mastil: Si", "Altura_Aprox_": "6 - 8 metros", "Estado": "Bueno", "Distrito": "Distrito Trapiche", "Observaciones_": "", "Fotos": "AsociacionVecinalJustoJoseUrquiza.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8552845, -32.9393017 ] } },
{ "type": "Feature", "properties": { "Name": "Barrio Sardi", "Nombre_Descripcion": "Barrio Sardi", "Ubicaci__n": "Paul Groussac y Olaya .P. de Tomba", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "", "Posee_Placa_Recordatoria": "", "Altura_Aprox_": "", "Estado": "", "Distrito": "Distrito Villa Marini", "Observaciones_": "", "Fotos": "BarrioSardi.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.85954875675903, -32.93726606086638 ] } }, 
{ "type": "Feature", "properties": { "Name": "Loteo Escala", "Nombre_Descripcion": "Loteo Escala", "Ubicaci__n": "Castroman y Corrientes", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "", "Posee_Placa_Recordatoria": "", "Altura_Aprox_": "", "Estado": "", "Distrito": "Distrito Las Tortugas", "Observaciones_": "", "Fotos": "LoteoEscala.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.83764635218033, -32.94727313244624 ] } }, 
{ "type": "Feature", "properties": { "Name": "Barrio Calise", "Nombre_Descripcion": "Barrio Calise", "Ubicaci__n": "Videla y Viamonte", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "", "Posee_Placa_Recordatoria": "", "Altura_Aprox_": "", "Estado": "", "Distrito": "Distrito Gobernador Benegas", "Observaciones_": "", "Fotos": "BarrioCalise.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.85045663378261, -32.94466445347027 ] } },
{ "type": "Feature", "properties": { "Name": "Barrio Villa mercedes", "Nombre_Descripcion": "Barrio Villa Mercedese", "Ubicaci__n": "Ohiggins y Paula Albarracin", "Posee_Mastil": "Posee Mastil: Si", "Posee_Bandera": "", "Posee_Placa_Recordatoria": "", "Altura_Aprox_": "", "Estado": "", "Distrito": "Distrito Villa Hipódromo", "Observaciones_": "", "Fotos": "BarrioVillaMercedes.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.85256320061623, -32.913269339428275 ] } },

]
}
