var SitiosyConjuntosEdilicios ={
"type": "FeatureCollection",
"name": "SitiosyConjuntosEdilicios",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": null, "Nombre": "PLAZOLETA EMILIO CIVIT", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "", "UBICACION": "Cervantes y Bolivia", "DISTRITO": "Distritos San Francisco del Monte", "USO": "Espacio verde recreativ", "PROPIETARI": null, "Fotos": "plazoletaEmilioCivit.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.839067523306653, -32.932832973019345 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "HOSPITAL DEL CARMEN", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construcción 1895 - 1900 Remodelación 1950", "UBICACION": "Joaquin V. Gonzalez 245", "DISTRITO": "Distrito Villa Marini", "USO": "Salud", "PROPIETARI": "Original Sociedad San Vicente de Paul Actual Ministerio de Salud Gobierno de Mendoza", "Fotos": "hospitaldelCarmen.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.859340698795705, -32.927288508990294 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "ANTIGUA BODEGA ARIZU", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construcción año 1888 - Remodelación año 1925 y 1940", "UBICACION": "Av, San Martín 1593", "DISTRITO": "Distrito Centro", "USO": "Establecimiento vitivinícola - Actual: sin uso", "PROPIETARI": "Original Sociedad Anónima Bodegas Arizu - Actual Municipalidad de Godoy Cruz", "Fotos": "bodegaArizu.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.843481892920323, -32.909154594216524 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "ANTIGUA BODEGA TOMBA (LUEGO EL GLOBO)", "Categor.": "Sitios y Conjutos Edilicios", "AÑO": "Construcción año 1885", "UBICACION": "Av. San Martin y Rivadavia", "DISTRITO": "Distrito Centro", "USO": "Original Establecimiento Vitivinícola - Actual en desuso", "PROPIETARI": "Propietarios original: Antonio Tomba y Hnos - actual: Pedro López e Hijos", "Fotos": "bodegaTomba.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.847132271887489, -32.923560981054649 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "ANTIGUA PLAZOLETA BIRITOS - (hoy EJERCITO LIBERTADOR)", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Propietario Original Familia Biritos", "UBICACION": "Alte. Brown - Biritos - Roque Saenz Peña", "DISTRITO": "Distrito Centro", "USO": "Espacio Verde recreativo", "PROPIETARI": "Original Familia Biritos - Actual Municipalidad de Godoy Cruz", "Fotos": "plazaBiritos.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.846381775614034, -32.910114880378543 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "FÁBRICA ISIDRO PEÑA y CIA. SRL.", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construcción año 1930", "UBICACION": "Perito Moreno 1697", "DISTRITO": "Distrito Gobernador Benegas", "USO": "Industrial - Fabrica", "PROPIETARI": "Original Isidro Peña y Asociados - Actual Maximo Peña", "Fotos": "IsidroPeña.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.849135916534607, -32.943993788573493 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "CLUB YPF (PETROLEROS)", "Categor.": "Sitios y Conjutos Edilicios", "AÑO": "Construcción año 1950 (primeros bloques)", "UBICACION": "Ingeniero Huergo 274", "DISTRITO": "Distrito Villa Marini", "USO": "Original  industrial - Actual recreativo", "PROPIETARI": null, "Fotos": "clubypf.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.85333870153498, -32.929540516479918 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "ESPACIO PESCARMONA (ANTIGUO PREDIO FFCC)", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construcción año 1900", "UBICACION": "Rivadavia - Balcarce Mitre", "DISTRITO": "Distrito Centro", "USO": "Original establecimiento ferroviario - Actual: espacio recreativo", "PROPIETARI": null, "Fotos": "espacioPescarmona.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.841863067194026, -32.924095447403339 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "FRIGORIFICO ACONCAGUA S.A.", "Categor.": "Sitios yConjuntos Edilicios  ", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construc. año 1820 Remodel. Fines siglo XIX - año 2001", "UBICACION": "Rivadavia - Perito Moreno Conjuntos Edilicios", "AÑO": "Construcción década de 1940", "UBICACION": "Los Alamos y Minuzzi", "DISTRITO": "Distrito Centro", "USO": "Comercial Frigorifico", "PROPIETARI": null, "Fotos": "frigorificioaconcagua.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.838543356058636, -32.907573559420292 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "PLAZA MAYOR TOMÁS GODOY CRUZ", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "construcción año 1820", "UBICACION": "Rivadavia Perito Moreno Lavalle Colón", "DISTRITO": "Distrito Centro", "USO": "Original: espacio público\/ plaza", "PROPIETARI": null, "Fotos": "plazaGodoyCruz.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.844370100776572, -32.925222462500095 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "PLAZOLETA ESCORIHUELA", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Propietario original  Familia Escorihuela", "UBICACION": "Presidente Alvear y Belgrano", "DISTRITO": "Distrito Centro", "USO": "espacio verde paseo", "PROPIETARI": "Original  Familia Escorihuela - Actua  Municipalidad de Godoy Cruz", "Fotos": "plazoletaEscorihuela.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.842744745671041, -32.912449624736873 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "ANTIGUO MATADERO MUNICIPAL", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construcción 1922 - 1923", "UBICACION": "Joaquin V. Gonzalez y Cipolletti", "DISTRITO": "Distrito Villa Marini", "USO": "Original: establecimiento industrial\/ Matadero Municipal \/ vivienda Actual Juzgados de Transito", "PROPIETARI": "Original Juan B. Mosso e Hijos Sociedad Anónima  Actual Municipalidad de Godoy Cruz", "Fotos": "matadero.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.858485452511758, -32.932727575269681 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "PUENTE FERROVIARIO", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construcción a principios del siglo XX", "UBICACION": "San Martin y Anzorena", "DISTRITO": "Distrito Centro", "USO": "Infraestructura ferroviaria", "PROPIETARI": null, "Fotos": "puenteavenidasanmartín.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.84610854073027, -32.916286842804396 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "PUENTE FERROVIARIO", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construccion a principios del siglo XX", "UBICACION": "Belgrano y Democracia", "DISTRITO": "Distrito Centro", "USO": "Infraestructura ferroviaria", "PROPIETARI": null, "Fotos": "puentecallebelgrano.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.843349843934291, -32.918579751142943 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "COLONIA 20 DE JUNIO", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construcción 1928 - 1946", "UBICACION": "Montes de Oca - Armani -  Corredor del Oeste", "DISTRITO": "Distrito Villa del Parque", "USO": "Original establecimiento de albergue  actual: establecimiento de albergue", "PROPIETARI": null, "Fotos": "colonia20dejunio.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.8654365354936, -32.918013975680594 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "HIPÓDROMO ANDINO DE MENDOZA", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construcción 1904 (pista)- 1949 (restaurante y torre)", "UBICACION": "Juncal y Montes de Oca", "DISTRITO": "Distrito Villa del Parque", "USO": null, "PROPIETARI": null, "Fotos": "hipodromo.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.867772116149752, -32.910913810485766 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "HOSPITAL JOSE NESTOR LENCINAS (Antiguo Hospital Carlos Ponce)", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construcción 1920 -  Remodelación década del 30", "UBICACION": "Talcahuano - Juncal - Las Tipas", "DISTRITO": "Distrito Villa del Parque", "USO": "Original equipamiento público\/ hospital", "PROPIETARI": null, "Fotos": "hospitallencinas.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.871033698541638, -32.903316710365587 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "CERVECERIA Y MALTERIA DE CUYO ANDES", "Categor.": "Sitios y Conuntos Edilicios", "AÑO": "Construcción 1922 -1923", "UBICACION": "Cervantes 2199", "DISTRITO": "Distrito Las Tortugas", "USO": "Industrial", "PROPIETARI": null, "Fotos": "cerveceriaandes.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.84664413780537, -32.951868008155927 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "CALVARIO Y CAPILLA JESUS DE NAZARENO, SEÑOR DE LA SALUD", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construcción 1940 - Remodelación 1996", "UBICACION": "Cervantes y Carrodilla", "DISTRITO": "Distrito Las Tortugas", "USO": "Oratorio Religioso", "PROPIETARI": "Arzobispado de Mendoza", "Fotos": "ElCalvario.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.852066341440462, -32.957932260349857 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "ANTIGUA BODEGA LA GERMANIA", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construccion año 1901", "UBICACION": "Carril Sarmiento 2198", "DISTRITO": "Distrito San Francisco del Monte", "USO": "Original Uso Industrial Bodega Vitivinicola", "PROPIETARI": "Heman, Albert y Pablo Wiedenbrug", "Fotos": "BodegaGermania.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.819089899011644, -32.942618366660696 ] } },
{ "type": "Feature", "properties": { "id": null, "Nombre": "CEMENTERIO DE GODOY CRUZ", "Categor.": "Sitios y Conjuntos Edilicios", "AÑO": "Construcción año: 1887    Remodelación: 2005", "UBICACION": "Carril Cervantes 700", "DISTRITO": "Distrito San Francisco del Monte", "USO": "Original Cementerio  público", "PROPIETARI": null, "Fotos": "cementerio.jpg" }, "geometry": { "type": "Point", "coordinates": [ -68.838653739935026, -32.933677322698543 ] } }
]
}
